 pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                echo "development building"
                ls -lrt
                '''

            }
        }
            stage('test'){
                steps {
                    sh '''
                    echo "testing the developmnt and doing some changes"
                    pwd
                    '''
                }
            }
        }
    }
 
