 pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                echo "adding some features"
                ls -lrt
                '''

            }
        }
            stage('test'){
                steps {
                    sh '''
                    echo "testing the features added"
                    pwd
                    '''
                }
            }
    }
  
 }
