 pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                echo "Building..."
                ls -lrt
                '''

            }
        }
            stage('test'){
                steps {
                    sh '''
                    echo "testing the build."
                    $JAVA_HOME
                    pwd
                    '''
                }
            }
        }
    }
 
